version: '3'

services:
  backend:
    image: resume.io-downloader-backend
    build:
      context: ./backend
    environment:
      GIN_MODE: release
      APP_PORT: 8080
    ports:
      - "8080:8080"
      
  frontend:
    image: resume.io-downloader-frontend
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - "4173:4173"
    depends_on:
      - backend
